EncDashboard/Models/AppSettings/CalcField.cs
namespace EncDashboard.Models.AppSettings
{
    public class CalcField
    {
        public string field { get; set; }
        public string calc { get; set; }
    }
}

EncDashboard/Models/AppSettings/Persona.cs
namespace EncDashboard.Models
{
    public class Persona
    {
        public string name { get; set; }
        public List<PipelineView> pipelineViews { get; set; }
    }

}

EncDashboard/Models/AppSettings/PersonasConfig.cs
namespace EncDashboard.Models
{
    public class PersonasConfig
    {
        public List<Persona> Personas { get; set; }
    }
}

EncDashboard/Models/AppSettings/PipelineView.cs
namespace EncDashboard.Models
{
    public class PipelineView
    {
        public string name { get; set; }
        public List<string> resultFields { get; set; }
    }
}

EncDashboard/Models/Loan/LoanRecords.cs
namespace EncDashboard.Models.Loan
{
    public class LoanRecords
    {
        public string loanId { get; set; }
        public Fields fields { get; set; }
    }
}

EncDashboard/Models/Others/LoanViewModel.cs
using EncDashboard.Models.PipelineViews;

namespace EncDashboard.Models.Others
{
    public class LoanViewModel
    {
        public List<Persona> Personas { get; set; }  
        public List<string> Columns { get; set; }

        public List<LoanRecords> LoanRecords { get; set; }
    }
}

EncDashboard/Models/PersonasConfig.cs
namespace EncDashboard.Models
{
    public class PersonasConfig
    {
        public List<string> UserPersonas { get; set; }
        public List<Persona> Personas { get; set; }
    }
}

EncDashboard/Models/PipelineView.cs
namespace EncDashboard.Models
{
    public class PipelineView
    {
        public string name { get; set; }
        public List<string> resultFields { get; set; }
        public List<CalcField> calcFields { get; set; }
    }
}

EncDashboard/Models/PipelineViews/Fields.cs
using Newtonsoft.Json;

namespace EncDashboard.Models.PipelineViews
{
    public class Fields
    {
        //Fields Getting From Apiwh
        [JsonProperty("Loan.LoanFolder")]
        public string LoanFolder { get; set; }

        [JsonProperty("Fields.4000")]
        public string Fields4000 { get; set; }

        [JsonProperty("Loan.LoanNumber")]
        public string LoanNumber { get; set; }

        [JsonProperty("Loan.LoanRate")]
        public string LoanRate { get; set; }

        [JsonProperty("Loan.LoanAmount")]
        public string LoanAmount { get; set; }

        [JsonProperty("Loan.LastModified")]
        public string LastModified { get; set; }

        [JsonProperty("Loan.BorrowerName")]
        public string BorrowerName { get; set; }

        [JsonProperty("Fields.745")]
        public string Fields745 { get; set; }

        [JsonProperty("Fields.CX.SUSPENDED.DATE")]
        public string FieldsCXSUSPENDEDDATE { get; set; }

        [JsonProperty("Fields.CX.PA.EXP")]
        public string FieldsCXPAEXP { get; set; }

        [JsonProperty("Log.MS.Date.Initial UW Review")]
        public string LogMSDateInitialUWReview { get; set; }


        //Calculated fields
        public string DaysToClosing { get; set; }
        public string DaysToSuspend { get; set; }

        public string DaysSinceUW { get; set; }

        public string DaysToExpire { get; set; }

    }
}

EncDashboard/Models/PipelineViews/LoanRecords.cs
namespace EncDashboard.Models.PipelineViews
{
    public class LoanRecords
    {
        public string loanId { get; set; }
        public Fields fields { get; set; }

    }
}

EncDashboard/Models/PipelineViews/LoanVIew/LoanViewRecords.cs
namespace EncDashboard.Models.Loan
{
    public class LoanViewRecords
    {
        public string loanId { get; set; }
        public Fields fields { get; set; }
    }
}

EncDashboard/Models/UserDetails/CcSite.cs
namespace EncDashboard.Models.UserDetails
{
    public class CcSite
    {
        public bool useParentInformation { get; set; }

    }
}

EncDashboard/Models/UserDetails/UserDetails.cs
namespace EncDashboard.Models.UserDetails
{
    public class UserDetails
    {
        
            public string id { get; set; }
            public string lastName { get; set; }
            public string firstName { get; set; }
            public string fullName { get; set; }
            public string email { get; set; }
            public string workingFolder { get; set; }
            public string subordinateLoanAccess { get; set; }
            public List<string> userIndicators { get; set; }
            public string peerLoanAccess { get; set; }
            public DateTime lastLogin { get; set; }
            public bool personalStatusOnline { get; set; }
            public string comments { get; set; }
            public List<UserPersona> personas { get; set; }
            public CcSite ccSite { get; set; }

    }
}

EncDashboard/Models/UserDetails/UserPersona.cs
namespace EncDashboard.Models.UserDetails
{
    public class UserPersona
    {
        public string entityId { get; set; }
        public string entityType { get; set; }
        public string entityName { get; set; }
    }
}

EncDashboard/Controllers/HomeController.cs
using EncDashboard.Services.ApiServices;
using Microsoft.AspNetCore.Mvc;

namespace EncDashboard.Controllers
{
    public class HomeController : Controller
    {
        private readonly IApiServices _apiServices;

        public HomeController(IApiServices apiServices)
        {
           _apiServices = apiServices;

        }

        public async Task<IActionResult> Index()
        {
            await _apiServices.getToken();
            await _apiServices.getUserDetails();
            return View();
        }

        

    }
}

EncDashboard/Controllers/LoanController.cs
using EncDashboard.Models;
using EncDashboard.Models.Others;
using EncDashboard.Services.ApiServices;
using EncDashboard.Services.AppSettingServices;
using Microsoft.AspNetCore.Mvc;

namespace EncDashboard.Controllers
{
    public class LoanController : Controller
    {
        private readonly IAppSettingsServices _appSettingsServices;
        private readonly IApiServices _apiServices;
        private static readonly LoanViewModel _loanViewModel = new LoanViewModel() { Personas = new List<Persona>(), Columns = new List<string>() };
        public LoanController(IAppSettingsServices appSettingsServices, IApiServices apiServices)
        {
            _appSettingsServices = appSettingsServices;
            _apiServices = apiServices;
        }

        public IActionResult PipelineViews()
        {
            try
            {
                var _matchingPersonas = _appSettingsServices.extractPersonas();
                _loanViewModel.Personas = _matchingPersonas;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }

            return View(_loanViewModel);
        }
        public async Task<LoanViewModel> filterQuery(string view)
        {
            try
            {
                foreach (var persona in _loanViewModel.Personas)
                {
                    foreach (var pipelineView in persona.pipelineViews)
                    {
                        if (view == pipelineView.name)
                        {
                            _loanViewModel.Columns = pipelineView.resultFields;

                        }
                    }

                }
                var records = await _apiServices.getLoanRecords(_loanViewModel.Columns, view);
                if (records != null)
                {
                    _loanViewModel.LoanRecords = records;
                }
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
            return _loanViewModel;
        }


    }
}

EncDashboard/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <!--<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>-->
</div>

@section views{

}

EncDashboard/Views/Loan/PipelineViews.cshtml
@{
    ViewData["Title"] = "Pipeline Views";
}
@model EncDashboard.Models.Others.LoanViewModel;

@section views {
    <ul class="navbar-nav flex-grow-2">
        @{
        var viewsList = new List<string>();
    }
        @foreach (var persona in Model.Personas)
        {
            @foreach (var pipelineView in persona.pipelineViews)
            {
                if (!viewsList.Contains(pipelineView.name))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" onclick="handleSelectChange('@pipelineView.name')">@pipelineView.name</a>
                    </li>
                    viewsList.Add(pipelineView.name);
                }
               
            }

        }
    </ul>
    }

<div id="partialViewContainer">
</div>

<div id="loader" class="loader"></div>

EncDashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EncDashboard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EncDashboard.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EncDashboard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Loan" asp-action="PipelineViews">Pipeline Views</a>
                        </li>
                    </ul>
                    @RenderSection("views")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <!--<div class="container">
            &copy; 2023 - EncDashboard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>-->
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>